services:
  cache:
    image: redis:7
    container_name: jabba-ai-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - jabba-ai-network

  mysql:
    image: mysql:8.0.39
    container_name: jabba-ai-db-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - jabba-ai-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mongo:
    image: mongo:7
    container_name: jabba-ai-db-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
    - jabba-ai-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - db-mongodb:/data/db
  db-mongodb-dashboard:
    image: mongo-express
    container_name: jabba-ai-db-mongodb-dashboard
    restart: unless-stopped
    ports:
      - "18081:8081"
    networks:
    - jabba-ai-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  redis-data:
  mysql_data:
    driver: local
  db-mongodb:


networks:
  jabba-ai-network:
    name: jabba-ai-network