services:
  cache:
    image: redis:7
    container_name: jabba-ai-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - jabba-ai-network

  mysql:
    image: mysql:8.0.39
    container_name: jabba-ai-db-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - jabba-ai-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


volumes:
  redis-data:
  mysql_data:
    driver: local


networks:
  jabba-ai-network:
    name: jabba-ai-network